###


GET http://localhost:3000/players/

###





###

POST http://localhost:3000/players/1/
Content-Type: application/json


###

GET http://localhost:3000/player/1/

###
PUT  http://localhost:3000/players/9/
Content-Type: application/json


###

DELETE  http://localhost:3000/players/1/